import {test,after} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {pool,OWNER_ID} from '../packages/db/src/index.ts';
import {buildApp} from '../apps/api/src/app.ts';
import {projectOne} from '../apps/worker/src/project.ts';
if(!new URL(process.env.DATABASE_URL!).pathname.startsWith('/knowscroll_test_')) throw new Error('Integration tests require an isolated knowscroll_test_* database');
const token='test-only-not-a-real-credential-123456';
const app=buildApp(token);const headers={authorization:`Bearer ${token}`};
after(async()=>{await app.close();await pool.end();});
test('real PostgreSQL: admission, retry, atomic projection, ownership and causal lineage',async()=>{
 assert.equal((await app.inject({url:'/v1/universe'})).statusCode,401);
 const feed=(await app.inject({url:'/v1/feed',headers})).json();const assetId=feed.items[0].assetId;
 assert.equal((await pool.query('SELECT count(*)::int AS n FROM exposure')).rows[0].n,0,'selection is not exposure');
 const exBody={decisionId:feed.decisionId,assetId,clientExposureId:randomUUID()};
 const ex=(await app.inject({method:'POST',url:'/v1/exposures',headers,payload:exBody})).json();
 assert.deepEqual((await app.inject({method:'POST',url:'/v1/exposures',headers,payload:exBody})).json(),ex);
 const body={clientEventId:randomUUID(),exposureId:ex.exposureId,assetId,kind:'keep'};
 const writes=await Promise.all(Array.from({length:8},()=>app.inject({method:'POST',url:'/v1/interactions',headers,payload:body})));
 assert.ok(writes.every(w=>w.statusCode===202));const receipt=writes[0]!.json();assert.ok(writes.every(w=>w.json().eventId===receipt.eventId));
 assert.equal((await pool.query('SELECT count(*)::int AS n FROM job')).rows[0].n,1);
 assert.equal((await pool.query('SELECT revision FROM accounts WHERE universe_id=$1',[OWNER_ID])).rows[0].revision,0,'admission is not projection');
 assert.equal((await app.inject({method:'POST',url:'/v1/interactions',headers,payload:{...body,assetId:feed.items[1].assetId}})).statusCode,409);
 assert.equal((await app.inject({method:'POST',url:'/v1/interactions',headers,payload:{...body,clientEventId:randomUUID(),exposureId:randomUUID()}})).statusCode,422);
 // Force a real database failure after projection begins; transaction must roll back.
 await pool.query("CREATE FUNCTION reject_projection() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'test crash'; END $$; CREATE TRIGGER reject_projection BEFORE UPDATE ON accounts FOR EACH ROW EXECUTE FUNCTION reject_projection()");
 await assert.rejects(projectOne);
 assert.equal((await pool.query('SELECT count(*)::int AS n FROM trace')).rows[0].n,0,'no half-applied Trace');
 await pool.query('DROP TRIGGER reject_projection ON accounts; DROP FUNCTION reject_projection()');
 await pool.query('UPDATE job SET available_at=now()');
 await Promise.all([projectOne(),projectOne()]);
 assert.equal((await pool.query('SELECT revision FROM accounts WHERE universe_id=$1',[OWNER_ID])).rows[0].revision,1);
 assert.equal(await projectOne(),null);
 const proof=(await app.inject({url:`/v1/events/${receipt.eventId}`,headers})).json();
 assert.equal(proof.causationId,ex.eventId);assert.equal(proof.exposureId,ex.exposureId);assert.equal(proof.projected,true);
 const next=(await app.inject({url:'/v1/feed',headers})).json();assert.ok(next.items.every((a:{assetId:string})=>a.assetId!==assetId));
 assert.equal((await app.inject({url:'/v1/universe',headers})).json().traces.length,1);
 assert.equal((await app.inject({url:'/v1/events/not-a-uuid',headers})).statusCode,400);
});
